import fs from 'fs';
import path from 'path';

// Parse local .env file if it exists
const envPath = path.resolve('.env');
let localEnv = {};

if (fs.existsSync(envPath)) {
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split('\n').forEach(line => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      localEnv[match[1].trim()] = match[2].trim();
    }
  });
}

// Merge process.env with local env
const env = { ...localEnv, ...process.env };

// Only generate if keys are present
if (env.FIREBASE_API_KEY) {
  const content = `// Auto-generated by generate-config.js during build
window.FIREBASE_CONFIG = {
  apiKey: "${env.FIREBASE_API_KEY}",
  authDomain: "${env.FIREBASE_AUTH_DOMAIN || ''}",
  projectId: "${env.FIREBASE_PROJECT_ID || ''}",
  storageBucket: "${env.FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${env.FIREBASE_MESSAGING_SENDER_ID || ''}",
  appId: "${env.FIREBASE_APP_ID || ''}"
};`;

  fs.writeFileSync('firebase-config.js', content);
  console.log('[Build] Successfully generated firebase-config.js');
} else {
  // Write an empty config if no keys found, letting the app fallback to simulation mode
  fs.writeFileSync('firebase-config.js', '/* No Firebase config found */');
  console.log('[Build] No Firebase credentials found. Running in simulation mode.');
}
